### ISSUE TITLE
Fix Plot Calls (Bug Report and Potential Fix)

### ISSUE THREAD

**Issue by HJ-UCSD** [Morriseylab/scViewer-Lite#1]
I recently cloned the repo and was not able to get it running and think I fixed the problem:

### **Issue:**

![image](https://user-images.githubusercontent.com/49694409/134995275-534d8b51-ce94-4785-beea-b2de4a4dce53.png)

Clicking the "Explore Data" to visualize the data breaks the app and produces the above output. 

### **Fix:**

Either change the initial Seurat object to have *umap* dimensional reduction calculations as it currently does not

![image](https://user-images.githubusercontent.com/49694409/134995542-5524d4cf-5ae3-457b-8ba8-266936ced9d8.png)

or change the reduction parameters in the Plot() calls to "tsne" to match the provided Seurat object

![image](https://user-images.githubusercontent.com/49694409/134995584-3f433d4b-3e41-452f-b31d-5865d890f9fd.png).

The latter option fixed the app for me, I am running R version 4.1.1 and Seurat version 4.0.4. I understand this application is meant for version 3 but I don't think it would change anything in this specific instance.

Also sorry I didn't submit a PR, I wasn't sure which fix y'all would take.

**Comment by bapoorva** [comment]
The code has been edited to now have a drop down menu listing all dimension reductions in the object and having the user select what they'd prefer instead of hardcoding it.
